finchcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    # route for finches index
    path('finches/', views.finches_index, name='index'),
    path('finches/create/', views.FinchCreate.as_view(), name='finches_create'),
    path('finches/<int:pk>/update/', views.FinchUpdate.as_view(), name='finches_update'),
    path('finches/<int:pk>/delete/', views.FinchDelete.as_view(), name='finches_delete'),
    path('finches/<int:finch_id>/add_sighting/', views.add_sighting, name='add_sighting'),
    path('finches/<int:finch_id>/assoc_food/<int:food_id>/', views.assoc_food, name='assoc_food'),
    path('finches/<int:finch_id>/unassoc_food/<int:food_id>/', views.unassoc_food, name='unassoc_food'),
    path('finches/<int:finch_id>/', views.finches_detail, name='detail'),
    path('foods/', views.FoodList.as_view(), name='foods_index'),
    path('foods/create/', views.FoodCreate.as_view(), name='foods_create'),
    path('foods/<int:pk>/update/', views.FoodUpdate.as_view(), name='foods_update'),
    path('foods/<int:pk>/delete/', views.FoodDelete.as_view(), name='foods_delete'),
    path('foods/<int:pk>/', views.FoodDetail.as_view(), name='foods_detail'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Food(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.color} {self.name}"
    
    def get_absolute_url(self):
        return reverse('foods_detail', kwargs={'pk': self.id})

class Finch(models.Model):
    name = models.CharField(max_length=100)
    wingspan = models.CharField(max_length=50)
    weight = models.CharField(max_length=50)
    description = models.TextField(max_length=500)

    foods = models.ManyToManyField(Food)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'finch_id': self.id})

class Sighting(models.Model):
    date = models.DateField('sighting date')
    location = models.CharField(max_length=100)

    finch = models.ForeignKey(Finch, on_delete=models.CASCADE)

    def __str__(self):
        return f"At {self.location} on {self.date}"
    
    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Sighting

class SightingForm(ModelForm):
    class Meta:
        model = Sighting
        fields = ['date', 'location']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from.models import Finch, Food
from .forms import SightingForm

# finches =[
#     {'name': 'European Goldfinch', 'wingspan': '21-25 cm', 'weight': '14-19 g', 'description': 'Male European goldfinches can often be distinguished by a larger, darker red mask that extends just behind the eye. The shoulder feathers are black, whereas they are brown on the female. In females, the red face does not extend past the eye. The ivory-coloured bill is long and pointed, and the tail is forked.'},
#     {'name': 'Hawfinch', 'wingspan': '29-33 cm', 'weight': '46-70 g', 'description': 'It is a robust bird with a thick neck, large round head and a wide, strong conical beak with a metallic appearance. It has short pinkish legs with a light hue and it has a short tail. It has brown eyes. The plumage of the female is slightly paler than that of the male. The overall colour is light brown, its head having an orange hue to it.'},
# ]

# Create your views here.

# define the home view
def home(request):
    # include an.html file extension
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def finches_index(request):
    finches = Finch.objects.all()
    return render(request, 'finches/index.html', { 'finches': finches })

def finches_detail(request, finch_id):
    finch = Finch.objects.get(id=finch_id)

    id_list = finch.foods.all().values_list('id')
    foods_finch_doesnt_have = Food.objects.exclude(id__in=id_list)

    sighting_form = SightingForm()
    return render(request, 'finches/detail.html', { 'finch': finch, 'sighting_form': sighting_form, 'foods': foods_finch_doesnt_have })

class FinchCreate(CreateView):
    model = Finch
    fields = ['name', 'wingspan', 'weight', 'description']

class FinchUpdate(UpdateView):
    model = Finch
    fields = ['wingspan', 'weight', 'description']

class FinchDelete(DeleteView):
    model = Finch
    success_url = '/finches/'

def add_sighting(request, finch_id):
    form = SightingForm(request.POST)

    if form.is_valid():
        new_sighting = form.save(commit=False)
        new_sighting.finch_id = finch_id
        new_sighting.save()
    return redirect('detail', finch_id=finch_id)

def assoc_food(request, finch_id, food_id):
    Finch.objects.get(id=finch_id).foods.add(food_id)
    return redirect('detail', finch_id=finch_id)

def unassoc_food(request, finch_id, food_id):
    Finch.objects.get(id=finch_id).foods.remove(food_id)
    return redirect('detail', finch_id=finch_id)

class FoodList(ListView):
    model = Food
    template_name = 'foods/index.html'

class FoodDetail(DetailView):
    model = Food
    template_name = 'foods/detail.html'

class FoodCreate(CreateView):
    model = Food
    fields = ['name', 'color']

    def form_valid(self, form):
        return super().form_valid(form)

class FoodUpdate(UpdateView):
    model = Food
    fields = ['name', 'color']

class FoodDelete(DeleteView):
    model = Food
    success_url = '/foods/'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}
    <h1>About the Finch Collector</h1>
    <hr>
    <p>Hire the Finch Collector!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Finch Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;Finch Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'finches_create' %}">Add a Finch</a></li>
          <li><a href="{% url 'index' %}">View All Finches</a></li>
          <li><a href="{% url 'foods_create' %}">Add a Food</a></li>
					<li><a href="{% url 'foods_index' %}">View All Foods</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2023 Finch Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/finches/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Finch Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ finch.name }}</span>
        <p>Wingspan: {{ finch.wingspan }}</p>
        <p>Weight: {{ finch.weight }}</p>
        <p>Description: {{ finch.description|linebreaks }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'finches_update' finch.id %}">Edit</a>
        <a href="{% url 'finches_delete' finch.id %}">Delete</a>
      </div>
    </div>
  </div>

  <div class="col s6">
    <form action="{% url 'add_sighting' finch.id %}" method="POST">
      {% csrf_token %} 
      {{ sighting_form.as_p }}
      <input type="submit" class="btn" value="Add Sighting">
    </form>
    <table class="striped">
      <thead>
        <tr><th>Sighting Date</th><th>Location</th></tr>
      </thead>
      <tbody>
        {% for sighting in finch.sighting_set.all %} 
          <tr>
            <td>{{sighting.date}}</td>
            <td>{{sighting.location}}</td>
          </tr>
          {% endfor %}
      </tbody>
    </table>
  </div>

</div>
  <hr>
  <div class="row">
    <div class="col s6">
      <h3>{{ finch.name }}'s Foods</h3>
      {% if finch.foods.count %}
        {% for food in finch.foods.all %}
          <div class="card">
            <div class="card-content">
              <span class="card-title">
                A <span style="color: {{ food.color }}">{{ food.color }}</span> {{ food.name }}
              </span>
            </div>
            <div class="card-action">
              <form action="{% url 'unassoc_food' finch.id food.id %}" method="POST">
                  {%csrf_token%}
                  <input type="submit" class="btn red" value="Remove">
              </form>
          </div>
          </div>
        {% endfor %}
      {% else %}
        <h5>No Foods</h5>
      {% endif %}
    </div>
    <div class="col s6">
      <h3>Available Foods</h3>
      {% if foods.count %}
        {% for food in foods.all %}
          <div class="card">
            <div class="card-content">
              <span class="card-title">
                A <span style="color: {{ food.color }}">{{ food.color }}</span> {{ food.name }}
              </span>
            </div>
            <div class="card-action">
              <form action="{% url 'assoc_food' finch.id food.id %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn">Add</button>
              </form>
            </div>
          </div>
        {% endfor %}
      {% endif %}
    </div>
  </div>
  
<script>
  const dateEl = document.getElementById('id_date')
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  })
</script>


{% endblock %}

main_app/templates/finches/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Finch List</h1>

{% for finch in finches %}
    <div class="card small">
        <div class="card-image">
            <img src="http://t3.gstatic.com/licensed-image?q=tbn:ANd9GcRT0fuYJ33kuGhuxWMvYnK--oQmg_rAzZqI8eAuSSJZ7KIf7q-w_oKysr2ElK8mZyfv2nCvFWI0hIyjj74" alt="{{finch.name}}">
            <span class="card-title">{{ finch.name }}</span>
        </div>
        <div class="card-content">
            <p>Wingspan: {{ finch.wingspan }}</p>
            <p>Weight: {{ finch.weight }}</p>
        </div>
        <div class="card-action">
            <a href="{% url 'detail' finch.id %}">View {{ finch.name }}</a>
        </div>
    </div>
{% endfor %}

{% endblock %}

main_app/templates/foods/detail.html
{% extends 'base.html' %} 
{% block content %} 
    <h1>Food Details</h1>

    <div class="card">
        <div class="card-content">
            <span class="card-title">
                A <span style="color: {{food.color}}">{{food.color}}</span> {{food.name}}
            </span>
        </div>
        <div class="card-action">
            <a class="btn" href="{% url 'foods_update' food.id %}">Edit</a>
            <a class="btn red" href="{% url 'foods_delete' food.id %}">Delete</a>
        </div>
    </div>

{% endblock %}

main_app/templates/foods/index.html
{% extends 'base.html' %} 
{% block content %} 

    <h1>Food List</h1>

    {% for food in object_list %} 
        <div class="card">
            <a href="{% url 'foods_detail' food.id %}">
                <div class="card-content">
                    <span class="card-title">
                        A <span style="color: {{food.color}}">{{food.color}}</span> {{food.name}}
                    </span>
                </div>
            </a>
        </div>
    {% endfor %}
{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}

{% block content %}
    <h1>Home</h1>
{% endblock %}

main_app/templates/main_app/finch_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Finch</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' finch.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/finch_form.html
{% extends 'base.html' %} 
{% block content %} 
{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Finch</h1>
{% endif %}
<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
    <input type="submit" value="Submit!" class="btn">
</form>

{% endblock %}

main_app/templates/main_app/food_confirm_delete.html
{% extends 'base.html' %}
{% block content %} 

    <h1>Delete Food</h1>

    <h4>Are you sure you want to delete <span class="teal-text">{{object.name}}</span></h4>

    <form action="" method="POST">
        {%csrf_token%} 

        <input type="submit" class="btn red" value="Yes, Delete">
        <a href="{% url 'detail' object.id %}" class="btn blue">Cancel</a>
    </form>

{% endblock %}

main_app/templates/main_app/food_form.html
{% extends 'base.html' %} 
{% block content %} 

    {% if object %} 
        <h1>Update {{object.name}}</h1>
    {%else%} 
    <h1>Add Food</h1>
    {% endif %}
    <form action="" method="POST">
        {%csrf_token%} 
        
        <table>{{form.as_table}}</table>
        <input type="submit" class="btn" value="{% if object %} Update Toy {% else %} Add Food {% endif %}">
    </form>

{% endblock %}